[build]
builder = "dockerfile"

[build.buildArgs]
DATABASE_URL = "${{DATABASE_URL}}"
RESEND_API_KEY = "${{RESEND_API_KEY}}"
NEXTAUTH_SECRET = "${{NEXTAUTH_SECRET}}"
NEXTAUTH_URL = "${{NEXTAUTH_URL}}"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "never"